# Generated by Django 4.2.16 on 2025-01-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_role_internship'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
                ('enrolled_to_tpo', models.IntegerField()),
                ('total_placed', models.IntegerField()),
                ('placement_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_ctc', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TopCompanyOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('ctc_in_lakhs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('academic_year', models.CharField(max_length=9)),
            ],
        ),
    ]
