# Generated by Django 4.2.16 on 2025-01-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('Placement', 'Placement'), ('Internship', 'Internship'), ('General', 'General')], max_length=50)),
                ('policy_title', models.CharField(max_length=255)),
                ('policy_text', models.TextField()),
            ],
        ),
    ]
