# Generated by Django 4.2.16 on 2025-01-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('policy_category', models.CharField(choices=[('Placement Policy', 'Placement Policy'), ('TPO VJTI Policy', 'TPO VJTI Policy')], default='Placement Policy', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
