# Generated by Django 4.2.16 on 2025-01-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_policyfaq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyfaq',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='policyfaq',
            name='policy_category',
        ),
        migrations.RemoveField(
            model_name='policyfaq',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='policyfaq',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='policyfaq',
            name='keywords',
            field=models.TextField(default='default'),
        ),
    ]
