# Generated by Django 5.1.5 on 2025-02-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_remove_policyfaq_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementstatistics',
            name='academic_year',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
