# Generated by Django 5.1.5 on 2025-02-10 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_placementstatistics_academic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyFAQ2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('policy_type', models.CharField(choices=[('Placement', 'Placement'), ('Internship', 'Internship'), ('Code of Conduct', 'Code of Conduct'), ('General', 'General')], default='General', max_length=50)),
                ('academic_year', models.CharField(blank=True, max_length=9, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('applicable_to', models.CharField(choices=[('BTech', 'BTech'), ('MTech', 'MTech'), ('MCA', 'MCA'), ('All', 'All')], default='All', max_length=50)),
                ('related_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.policyfaq2')),
            ],
        ),
    ]
