# Generated by Django 5.1.5 on 2025-03-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_policyfaq2'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyfaq',
            name='embedding',
            field=models.JSONField(null=True),
        ),
    ]
