# Generated by Django 5.1.5 on 2025-03-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_policyfaq_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyfaq',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
