# Generated by Django 5.1.5 on 2025-03-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_alter_policyfaq_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
