# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20250129-163031-bipartite-sky

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

version: "3.1"

pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 3
    max_ngram: 5
  - name: DIETClassifier
    epochs: 200  # Increased from 100 to 200 for better accuracy
    entity_recognition: False
  - name: ResponseSelector
    epochs: 150  # Increased training time for better response selection
  - name: FallbackClassifier
    threshold: 0.4  # Increased from 0.2 to 0.4 to avoid incorrect low-confidence responses


policies:
- name: RulePolicy
