# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20250129-163031-bipartite-sky

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

version: "3.1"

pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 3
    max_ngram: 5
  - name: DIETClassifier
    epochs: 100
    entity_recognition: False
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.2

policies:
- name: RulePolicy
